
package br.com.visao.aluno;

import br.com.controle.Aluno;
import br.com.modelo.AlunoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class CadastrarAluno extends javax.swing.JFrame {

    
    public CadastrarAluno() {
        initComponents();
        try{
               AlunoDAO  ad = new AlunoDAO();
               Aluno a = new Aluno();
               
            ArrayList<Aluno> aluno = ad.PesquisarTudoC();
            for(int i = 0; i < aluno.size();i++){
                a = aluno.get(i);
                jCcurso.addItem(a);
            }
        }
            catch(Exception e){
            System.out.println("Erro " + e.getMessage());
            }
        try{
               AlunoDAO  adc = new AlunoDAO();
               Aluno ab = new Aluno();
               
            ArrayList<Aluno> aluno = adc.PesquisarTudoT();
            for(int i = 0; i < aluno.size();i++){
                ab = aluno.get(i);
                jCturma.addItem(ab);
            }
        }
            catch(Exception e){
            System.out.println("Erro " + e.getMessage());
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jTidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTuser = new javax.swing.JTextField();
        jTpass = new javax.swing.JPasswordField();
        jRadioButton = new javax.swing.JRadioButton();
        jBcadastrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jCcurso = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCturma = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jLabel1.setText("Cadastro de Aluno");

        jLabel2.setText("Nome:");

        jLabel4.setText("Idade:");

        jLabel3.setText("Email:");

        jLabel5.setText("Usuário:");

        jRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonActionPerformed(evt);
            }
        });

        jBcadastrar.setText("Cadastrar");
        jBcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarActionPerformed(evt);
            }
        });

        jLabel7.setText("Senha:");

        jCcurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecionar>" }));
        jCcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcursoActionPerformed(evt);
            }
        });

        jLabel6.setText("Curso");

        jLabel8.setText("Turma:");

        jCturma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecionar>" }));
        jCturma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCturmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTidade, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTemail, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCturma, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTpass, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jRadioButton))
                            .addComponent(jTuser, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jBcadastrar)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel2)
                    .addContainerGap(227, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCturma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(29, 29, 29)
                .addComponent(jBcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(jLabel2)
                    .addContainerGap(312, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonActionPerformed
        if(jRadioButton.isSelected()){
            jTpass.setEchoChar('\u0000');
        }else{
            jTpass.setEchoChar('*');
        }
    }//GEN-LAST:event_jRadioButtonActionPerformed

    private void jBcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarActionPerformed
        // TODO add your handling here:
         AlunoDAO pdao = new AlunoDAO();
        if(jTnome.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o nome do professor!");
            jTnome.requestFocus();
        }else{
           if(jTemail.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o email!");
            jTemail.requestFocus();}
           else{
            if(jCcurso.getSelectedItem().equals("<Selecionar>")){
                JOptionPane.showMessageDialog(null, "Escolha a disciplina!");
                jCcurso.requestFocus();
            }else{
                if(jTidade.getText().trim().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Preencha a idade!");
                    jTidade.requestFocus();}
                else{
                    if(jTuser.getText().trim().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Preencha o nome de usuario!");
                    jTuser.requestFocus();}
                    else{
                        if(jTpass.getText().trim().isEmpty()){
                           JOptionPane.showMessageDialog(null, "Preencha a senha!");
                           jTpass.requestFocus();
                    }
                
                try{
                Aluno aluno = (Aluno) jCcurso.getSelectedItem();
                Aluno alunob = (Aluno) jCturma.getSelectedItem();
                aluno.setNome(jTnome.getText());
                aluno.setEmail(jTemail.getText());
                aluno.setIdade(Integer.valueOf(jTidade.getText()));
                aluno.setUsuario(jTuser.getText());
                aluno.setSenha(jTpass.getText());
                
                if(pdao.verificarProf(jTemail.getText())){
                    JOptionPane.showMessageDialog(null,"O email "+aluno.getEmail()+" ja esta cadastrado:");
                }
                else{
                     if(pdao.verificarU(jTuser.getText())){
                     JOptionPane.showMessageDialog(null,"O usuario "+aluno.getUsuario()+" ja esta cadastrado:");
                }else{
                pdao.validaAluno(aluno);
                pdao.inserirAluno(aluno,alunob);
                pdao.inserirAlunoU(aluno);

            
                
                jTnome.setText(null);
                jCcurso.setSelectedItem(null);
                jCturma.setSelectedItem(null);
                jTemail.setText(null);
                jTidade.setText(null);
                jTuser.setText(null);
                jTpass.setText(null);
                jTnome.requestFocus();
                
                
                }
                }
             }
                catch(Exception ex) {
                    System.out.println("erro" + ex);  
                }
            }
        }  
      }
    }
        }
    }//GEN-LAST:event_jBcadastrarActionPerformed

    private void jCcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCcursoActionPerformed

    private void jCturmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCturmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCturmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcadastrar;
    private javax.swing.JComboBox<Object> jCcurso;
    private javax.swing.JComboBox<Object> jCturma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton;
    private javax.swing.JTextField jTemail;
    private javax.swing.JTextField jTidade;
    private javax.swing.JTextField jTnome;
    private javax.swing.JPasswordField jTpass;
    private javax.swing.JTextField jTuser;
    // End of variables declaration//GEN-END:variables
}
